## YAML Template.
---
openapi: 3.0.0
info:
  title: Lanchonete Online API
  version: 1.0.0
paths:
  /salvarBebida:
    post:
      summary: Save Beverage Data
      description: Endpoint to save beverage data in the Lanchonete Online application.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: The name of the beverage.
                descricao:
                  type: string
                  description: The description of the beverage.
                quantidade:
                  type: integer
                  description: The quantity of the beverage.
                ValorCompra:
                  type: number
                  description: The purchase value of the beverage.
                ValorVenda:
                  type: number
                  description: The selling value of the beverage.
                tipo:
                  type: string
                  description: The type or category of the beverage.
              required:
                - nome
                - descricao
                - quantidade
                - ValorCompra
                - ValorVenda
                - tipo
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: "Beverage saved!"
        '400':
          description: Bad Request
          content:
            application/json:
              example: "Error: Bad Request"
        '500':
          description: Internal Server Error
          content:
            application/json:
              example: "Error: Internal Server Error"


openapi: 3.0.0
info:
  title: Lanchonete Online API
  version: 1.0.0
paths:
  /salvarLanche:
    post:
      summary: Salvar Lanche Personalizado
      description: Endpoint para salvar um lanche personalizado na Lanchonete Online.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do lanche.
                descricao:
                  type: string
                  description: Descrição do lanche.
                ValorVenda:
                  type: number
                  description: Valor de venda do lanche.
                ingredientes:
                  type: object
                  description: Lista de ingredientes do lanche com suas quantidades.
                  additionalProperties:
                    type: integer
              required:
                - nome
                - descricao
                - ValorVenda
                - ingredientes
      responses:
        '200':
          description: Resposta bem-sucedida
          content:
            application/json:
              example: "Lanche Salvo com Sucesso!"
        '400':
          description: Solicitação Inválida
          content:
            application/json:
              example: "Erro: Solicitação Inválida"
        '500':
          description: Erro Interno do Servidor
          content:
            application/json:
              example: "Erro: Erro Interno do Servidor"


openapi: 3.0.0
info:
  title: Lanchonete Online API
  version: 1.0.0
paths:
  /salvarIngrediente:
    post:
      summary: Salvar Ingrediente
      description: Endpoint para salvar um novo ingrediente na lista de produtos da Lanchonete Online.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do ingrediente.
                descricao:
                  type: string
                  description: Descrição do ingrediente.
                quantidade:
                  type: integer
                  description: Quantidade disponível do ingrediente.
                ValorCompra:
                  type: number
                  description: Valor de compra do ingrediente.
                ValorVenda:
                  type: number
                  description: Valor de venda do ingrediente.
                tipo:
                  type: string
                  description: Tipo ou categoria do ingrediente.
              required:
                - nome
                - descricao
                - quantidade
                - ValorCompra
                - ValorVenda
                - tipo
      responses:
        '200':
          description: Resposta bem-sucedida
          content:
            application/json:
              example: "Ingrediente Salvo!"
        '400':
          description: Solicitação Inválida
          content:
            application/json:
              example: "Erro: Solicitação Inválida"
        '500':
          description: Erro Interno do Servidor
          content:
            application/json:
              example: "Erro: Erro Interno do Servidor"

openapi: 3.0.0
info:
  title: Lanchonete Online API
  version: 1.0.0
paths:
  /removerBebida:
    post:
      summary: Remover Bebida
      description: Endpoint para remover uma bebida do sistema da Lanchonete Online.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ID da bebida a ser removida.
                nome:
                  type: string
                  description: Nome da bebida.
                descricao:
                  type: string
                  description: Descrição da bebida.
                quantidade:
                  type: integer
                  description: Quantidade disponível da bebida.
                ValorCompra:
                  type: number
                  description: Valor de compra da bebida.
                ValorVenda:
                  type: number
                  description: Valor de venda da bebida.
                tipo:
                  type: string
                  description: Tipo ou categoria da bebida.
              required:
                - id
                - nome
                - descricao
                - quantidade
                - ValorCompra
                - ValorVenda
                - tipo
      responses:
        '200':
          description: Resposta bem-sucedida
          content:
            application/json:
              example: "Bebida Removida!"
        '400':
          description: Solicitação Inválida
          content:
            application/json:
              example: "Erro: Solicitação Inválida"
        '500':
          description: Erro Interno do Servidor
          content:
            application/json:
              example: "Erro: Erro Interno do Servidor"

openapi: 3.0.0
info:
  title: Lanchonete Online API
  version: 1.0.0
paths:
  /alterarBebida:
    post:
      summary: Alterar Bebida
      description: Endpoint para alterar os detalhes de uma bebida no sistema da Lanchonete Online.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ID da bebida a ser alterada.
                nome:
                  type: string
                  description: Novo nome da bebida.
                descricao:
                  type: string
                  description: Nova descrição da bebida.
                quantidade:
                  type: integer
                  description: Nova quantidade disponível da bebida.
                ValorCompra:
                  type: number
                  description: Novo valor de compra da bebida.
                ValorVenda:
                  type: number
                  description: Novo valor de venda da bebida.
                tipo:
                  type: string
                  description: Novo tipo ou categoria da bebida.
              required:
                - id
                - nome
                - descricao
                - quantidade
                - ValorCompra
                - ValorVenda
                - tipo
      responses:
        '200':
          description: Resposta bem-sucedida
          content:
            application/json:
              example: "Bebida Alterada!"
        '400':
          description: Solicitação Inválida
          content:
            application/json:
              example: "Erro: Solicitação Inválida"
        '500':
          description: Erro Interno do Servidor
          content:
            application/json:
              example: "Erro: Erro Interno do Servidor"
